name: Build and publish Docker image ðŸš€

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
    paths:
      - 'apps/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'apps/**'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-wallos:
    uses: ./.github/workflows/docker-publish-template.yml
    with:
      image_name: wallos
      context: ./apps/wallos
      dockerfile: ./apps/wallos/Dockerfile